[nltk_data] Downloading package stopwords to
[nltk_data]     /home/kit/stud/ucgvm/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /home/kit/stud/ucgvm/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
22:49:11 - WARNING - root - Added new config entry: "output_dir"
22:49:11 - WARNING - train - No observers have been added to this run
22:49:11 - INFO - train - Running command 'link_prediction'
22:49:11 - INFO - train - Started
22:49:11 - INFO - link_prediction - CUDA devices used: 2
22:49:11 - ERROR - train - Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "train.py", line 278, in link_prediction
    tokenizer = GloVeTokenizer('data/glove/glove.6B.300d-maps.pt')
  File "/pfs/data5/home/kit/stud/ucgvm/blp/data.py", line 303, in __init__
    self.word2idx = torch.load(vocab_dict_file)
  File "/pfs/data5/home/kit/stud/ucgvm/environment/lib64/python3.6/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/pfs/data5/home/kit/stud/ucgvm/environment/lib64/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/pfs/data5/home/kit/stud/ucgvm/environment/lib64/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/glove/glove.6B.300d-maps.pt'


============================= JOB FEEDBACK =============================

NodeName=uc2n485
Job ID: 20499172
Cluster: uc2
User/Group: ucgvm/stud
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 40
CPU Utilized: 00:00:08
CPU Efficiency: 0.61% of 00:22:00 core-walltime
Job Wall-clock time: 00:00:33
Memory Utilized: 2.31 MB
Memory Efficiency: 0.00% of 0.00 MB
